### PR TITLE
Add option to publish setMachineState

### PR DESCRIPTION
**Pull request by Loghorn**
This change will add a new optional parameter to `Stately` constructor to allow the direct access to the `setMachineState` method.

### CODE REVIEW

**Comment by fschaefer** [comment]
@Loghorn,

thank you very much for contributing and opening a pull request! Do you mind explaining a bit about your intention to expose these methods? `setMachineState()` et al. are not exposed on purpose (i.e. to not change the internal state of the maschine from the outside).

**Comment by Loghorn** [comment]
@fschaefer I know that the methods to directly change the internal change are protected on purpose and that's the reason I added an explicit option, but for my use case I need them. I'm using stately.js to model a virtual keyboard to allow users using only a remote with a device (like a smart tv) to type text; it works great: each key is a state and the keypress of the remote move to the adjacent state in the appropriate direction. But my problem is that you could also connect a mouse to the device, so when you move the pointer over a key I need to change the internal state of Stately.js to match, because the user can mix the use of mouse and remote.

**Comment by fschaefer** [comment]
@Loghorn,
I can see your point, but I prefer to not change the API in that way, as it seems paradox to me to protect the state of the machine and then to expose these functions anyway.

In general, I think it's not a good idea to change the internal state of a state machine from the outside without an event. So a "proper" solution would be to attach a "mouseMovedOverKey" event to every state object. Something like this:

```
function attachToEveryState(fnObject, stateObject) {
    Object.keys(fnObject).forEach(function(fn) {
        Object.keys(stateObject).forEach(function(state) {
            stateObject[state][fn] = fnObject[fn];
        });
    });
    return stateObject;
}

var vk = Stately.machine(
    attachToEveryState(
        {
            "mouseMovedOverKey": function (key) { return [key] }
        },
        {
            'A': {
            },
            'S': {
            },
            'D': {
            },
            'F': {
            }
        }
    )
);

vk.mouseMovedOverKey("S")
vk.getMachineState() /* <- S */
```

It's effectively the same thing but keeps the idea of the state machine clean.

**Comment by Loghorn** [comment]
You are right, that's a much cleaner solution.
Thank you.

**Pull request closed without merging**
